<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Campaignmonitor\Module'                        => __DIR__ . '/Module.php',
    'Campaignmonitor\Controller\IndexController' => __DIR__ . '/src/Campaignmonitor/Controller/IndexController.php',
    'CampaignmonitorTest\Framework\TestCase'        => __DIR__ . '/tests/Campaignmonitor/Framework/TestCase.php',
    'CampaignmonitorTest\SampleTest'                => __DIR__ . '/tests/Campaignmonitor/SampleTest.php',
);
